[package]
name = "my_project"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version="1.44",features = ["full"]}
reqwest = {version="0.12",features=["json"]}
serde_json="1.0"
anyhow="1.0"
